version: '3'

services:
  cassandra:
    image: cassandra:3
    expose:
    - "9042"
    ports:
    - "9042:9042"
  db_init:
    image: cassandra:3
    volumes:
    - ./init.cql:/init.cql
    - ./init.sh:/init.sh
    - semaphore-volume:/tmp/sema
    command: ["sh", "/init.sh"]
    links:
    - cassandra
    depends_on:
    - cassandra
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.2
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic1:2:1"
    links:
    - zookeeper:zookeeper
    depends_on:
    - zookeeper
  misl_wrapper:
    image: honeywellmovilizer/mislproxy:1.0
    links:
    - cassandra:cassandra
    - kafka:kafka
    command:
    - /usr/bin/run.sh
    volumes:
    - ./run.sh:/usr/bin/run.sh
    - semaphore-volume:/tmp/sema
    environment:
    - MW_KAFKA=kafka:9092
    - MW_CASSANDRA=cassandra:9042
    - MW_SYSTEM_ID=10002
    - MW_BACKENDS=/etc/misl-wrapper/endpoints
    - MW_GRPC_PORT=10000
    depends_on:
    - kafka
    - db_init
    ports:
    - "10000:10000"
    expose:
    - "10000"
volumes:
  semaphore-volume: